#!/bin/sh

finish() {
    trap '' SIGINT SIGTERM
    kill -TERM $(jobs -p)
    exit 1
}
trap finish SIGINT SIGTERM

scripts="../../rgw-w-race-test"

if pwd | grep -q "build$" ;then
    :
else
    echo run from build directory
    exit 1
fi

while true ; do
    lsof -i :40766 -P -n
    while [ -n "$(lsof -i :40766 -P -n)" ] ; do
	echo "MONITOR PORT OPEN"
	lsof -i :40766 -P -n
	../src/stop.sh
	sleep 1
    done

    echo CLEANING
    rm -rf out/* dev/*

    echo STARTING
    ${scripts}/my-new-vstart

    echo DELETING AND CREATING
    ${scripts}/delete_create_script.sh

    echo COUNTING
    count=$(${scripts}/list_objects.sh | wc -l)
    if [ $count -gt 0 ] ;then
	break
    fi

    echo STOPPING
    ../src/stop.sh
done

${scripts}/list_objects.sh | tee list_objects.out
../src/stop.sh
bell
